try {
    throw new Error('Algo sali√≥ mal');
} catch {
    console.log('Hubo un error bastante grave...');
}